name: wordpress-downstreamer-2
recipe: wordpress

services:
  database:
    type: wordpress-mysql:8.0

# do not remove this
plugins:
  "@lando/wordpress": ../..
  "@lando/mysql": ../../node_modules/@lando/mysql
